const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const esbuild=require('esbuild');
const root=path.resolve(__dirname,'..');const out=path.join(__dirname,'core-bundle.cjs');
esbuild.buildSync({entryPoints:[path.join(root,'src/core.js')],outfile:out,bundle:true,platform:'node',target:'node22',format:'cjs',loader:{'.wasm':'binary'},define:{'import.meta.url':'"file:///mori-unused-async-loader"'},nodePaths:[process.env.NODE_PATH||path.join(root,'node_modules')]});
const c=require(out);let count=0;const tests=[];function test(name,fn){try{fn();count++;tests.push({name,pass:true});}catch(e){tests.push({name,pass:false,error:e.message});}}
const text='ᠮᠣᠩᠭᠣᠯ\u180B\u180C\u180D\u180E\u180F\u202F\u200D\u200C\n中文 😀';
test('UTF8 exact control preservation',()=>assert.equal(c.decodeBytes(new TextEncoder().encode(text)).text,text));
test('UTF16 LE BOM',()=>assert.equal(c.decodeBytes(Uint8Array.from([255,254,32,24])).text,'ᠠ'));
test('UTF16 BE BOM',()=>assert.equal(c.decodeBytes(Uint8Array.from([254,255,24,32])).text,'ᠠ'));
test('Reject invalid UTF8',()=>assert.throws(()=>c.decodeBytes(Uint8Array.from([255]))));
test('Explicit GB18030 basic character',()=>assert.equal(c.decodeBytes(Uint8Array.from([214,208]),'gb18030').text,'中'));
test('GB18030 Mongolian 4-byte sequence',()=>{const t=c.decodeBytes(Uint8Array.from([0x81,0x34,0xd6,0x30]),'gb18030').text;assert.equal(t,'ᠠ');});
test('Codepoint stats include supplementary plane',()=>assert.equal(c.inspectText('ᠮ😀').characters,2));
test('PUA is not automatically Menksoft',()=>assert.equal(c.inspectText('\uE000\uE264\u{F0000}').pua,3));
test('Plaintext paragraph roundtrip',()=>assert.equal(c.plainText(c.textDocument(text)),text));
test('Base64 original bytes roundtrip',()=>{const a=Uint8Array.from([0,255,128,1]);assert.deepEqual(c.b64ToBytes(c.bytesToB64(a)),a);});
test('Document valid JSON roundtrip',()=>{const d=c.validateFile({format:'mori-document',version:1,title:'测试',profile:'2010',doc:c.textDocument(text).toJSON()});assert.equal(c.plainText(d.doc),text);assert.equal(d.profile,'2010');});
test('Unsupported document version rejected',()=>assert.throws(()=>c.validateFile({format:'mori-document',version:99})));
test('Unsafe node rejected',()=>assert.throws(()=>c.validateFile({format:'mori-document',version:1,title:'X',profile:'2023',doc:{type:'script'}})));
test('Color injection sanitized',()=>assert.equal(c.safeColor('red; background:url(https://x)'), '#26312c'));
test('HTML serialization escaping',()=>assert.equal(c.escapeHTML('<script>"&'),'&lt;script&gt;&quot;&amp;'));
test('Converter pinned version',()=>assert.equal(c.initConverter(),'0.7.1'));
test('Menksoft forward and reverse',()=>{const a=c.convertText('utn57','menk_shape','ᠮᠣᠩᠭᠣᠯ');assert.ok(c.inspectText(a.text).pua>0);const b=c.convertText('menk_shape','utn57',a.text);assert.ok(/[\u1820-\u1842]/u.test(b.text));});
test('Unsupported converter profile rejected',()=>assert.throws(()=>c.convertText('oyun','utn57','x')));
test('Unknown non-Mongolian characters preserved',()=>assert.equal(c.convertText('menk_shape','utn57','ABC 中文 😀').text,'ABC 中文 😀'));
test('Independent profiles do not modify text',()=>{for(const p of Object.keys(c.profiles)){const d=c.validateFile({format:'mori-document',version:1,title:'测试',profile:p,doc:c.textDocument(text).toJSON()});assert.equal(c.plainText(d.doc),text);}});
test('Lossy conversion explicitly flagged',()=>{const r=c.convertText('utn57','menk_shape','ᠮᠣᠩᠭᠣᠯ');assert.equal(r.roundTripExact,false);assert.ok(r.warnings.some(w=>w.includes('不能无损')));});
test('A4 landscape geometry',()=>{const g=c.pageGeometry(c.normalizePage({size:'A4',orientation:'landscape',margins:{top:20,right:20,bottom:20,left:20}}));assert.equal(Math.round(g.widthMm),297);assert.equal(Math.round(g.heightMm),210);assert.equal(Math.round(g.contentWidthMm),257);assert.equal(Math.round(g.contentHeightMm),170);});
test('content box subtracts the matching margins',()=>{const g=c.pageGeometry(c.normalizePage({size:'A4',orientation:'landscape',margins:{top:30,right:10,bottom:5,left:10}}));assert.equal(Math.round(g.contentWidthMm),277);assert.equal(Math.round(g.contentHeightMm),175);});
test('A4 portrait geometry',()=>{const g=c.pageGeometry(c.normalizePage({size:'A4',orientation:'portrait'}));assert.equal(Math.round(g.widthMm),210);assert.equal(Math.round(g.heightMm),297);});
test('A3 landscape geometry',()=>{const g=c.pageGeometry(c.normalizePage({size:'A3',orientation:'landscape'}));assert.equal(Math.round(g.widthMm),420);assert.equal(Math.round(g.heightMm),297);});
test('page margins clamped to 5..50',()=>{const p=c.normalizePage({margins:{top:1,right:999,bottom:20,left:20}});assert.equal(p.margins.top,5);assert.equal(p.margins.right,50);});
test('unknown page size falls back to A4',()=>assert.equal(c.normalizePage({size:'B5'}).size,'A4'));
test('page summary describes orientation',()=>assert.match(c.pageSummary({size:'A4',orientation:'landscape',margins:{top:20,right:20,bottom:20,left:20}}),/A4 横向/));
test('legacy string page setting migrates',()=>{const d=c.validateFile({format:'mori-document',version:1,title:'T',profile:'2023',settings:{page:'A3'},doc:c.textDocument('x').toJSON()});assert.equal(d.settings.page.size,'A3');assert.equal(d.settings.page.orientation,'landscape');});
test('version 2 documents accepted',()=>{const d=c.validateFile({format:'mori-document',version:2,title:'T',profile:'2023',doc:c.textDocument('x').toJSON()});assert.equal(d.doc.textContent,'x');});
test('pagination fills pages up to capacity',()=>{const r=c.paginateBlocks(Array.from({length:10},()=>({length:100})),{contentHeight:1000,capacity:4});assert.equal(r.totalPages,3);assert.equal(r.pages.flat().length,10);assert.deepEqual(r.pages.map(p=>p.length),[4,4,2]);});
test('pagination flags oversized blocks',()=>{const r=c.paginateBlocks([{length:5000}],{contentHeight:1000,capacity:2});assert.equal(r.overflow.length,1);assert.equal(r.pages.length,1);});
test('pagination accounts for heading weight',()=>{const r=c.paginateBlocks([{length:100,weight:2},{length:100,weight:1}],{contentHeight:1000,capacity:3});assert.equal(r.totalPages,1);assert.equal(r.pages[0].length,2);});
test('pagination wraps when weight overflows',()=>{const r=c.paginateBlocks([{length:100,weight:2},{length:100,weight:2},{length:100,weight:2}],{contentHeight:1000,capacity:4});assert.equal(r.totalPages,2);});
test('pagination handles empty document',()=>{const r=c.paginateBlocks([],{contentHeight:100,capacity:1});assert.equal(r.totalPages,1);assert.deepEqual(r.pages,[[]]);});
test('pagination rejects invalid capacity',()=>assert.throws(()=>c.paginateBlocks([],{contentHeight:100,capacity:0})));
test('pagination rejects invalid content height',()=>assert.throws(()=>c.paginateBlocks([],{contentHeight:0,capacity:1})));
test('schema supports heading levels 1-3',()=>{for(const level of [1,2,3]){const n=c.schema.nodes.heading.create({level},c.schema.text('x'));assert.equal(n.attrs.level,level);}});
test('heading DOM reflects level',()=>{const n=c.schema.nodes.heading.create({level:3},c.schema.text('x'));assert.equal(n.type.spec.toDOM(n)[0],'h3');});
test('textStyle mark carries font and size',()=>{const m=c.schema.marks.textStyle.create({fontFamily:'Heiti SC',fontSize:32});assert.equal(m.attrs.fontFamily,'Heiti SC');assert.equal(m.attrs.fontSize,32);});
test('textStyle DOM quotes family and emits px size',()=>{const m=c.schema.marks.textStyle.create({fontFamily:'Heiti SC',fontSize:32});const dom=m.type.spec.toDOM(m);assert.match(dom[1].style,/font-family:"Heiti SC"/);assert.match(dom[1].style,/font-size:32px/);});
test('font name injection sanitized',()=>assert.equal(c.safeFont('x"; background:url(//evil)'),'Mori Noto'));
test('font size out of range rejected',()=>assert.equal(c.safeSize(9999),null));
test('superscript and subscript exclude each other',()=>{assert.equal(c.schema.marks.sup.spec.excludes,'sub');assert.equal(c.schema.marks.sub.spec.excludes,'sup');});
test('block attributes render inline style',()=>{const n=c.schema.nodes.paragraph.create({align:'center',indent:2,firstLine:2,leading:1.4},c.schema.text('x'));const style=n.type.spec.toDOM(n)[1].style;assert.match(style,/text-align:center/);assert.match(style,/margin-block-start:2em/);assert.match(style,/text-indent:2em/);assert.match(style,/line-height:1\.4/);});
test('block without attributes renders no style',()=>{const n=c.schema.nodes.paragraph.create(null,c.schema.text('x'));assert.equal(n.type.spec.toDOM(n).length,2);});
test('cssString quotes plain font names',()=>assert.equal(c.cssString('Mongolian Baiti'),'"Mongolian Baiti"'));
test('paragraph attrs survive JSON roundtrip',()=>{const doc=c.schema.node('doc',null,[c.schema.nodes.paragraph.create({align:'end',indent:3,leading:2.1},c.schema.text('ᠮᠣᠩᠭᠣᠯ'))]);const back=c.schema.nodeFromJSON(JSON.parse(JSON.stringify(doc.toJSON())));assert.equal(back.firstChild.attrs.align,'end');assert.equal(back.firstChild.attrs.indent,3);assert.equal(back.firstChild.attrs.leading,2.1);assert.equal(back.textContent,'ᠮᠣᠩᠭᠣᠯ');});
test('mark attrs survive JSON roundtrip',()=>{const doc=c.schema.node('doc',null,[c.schema.nodes.paragraph.create(null,c.schema.text('ᠮ',[c.schema.marks.textStyle.create({fontFamily:'Menksoft',fontSize:40})]))]);const back=c.schema.nodeFromJSON(JSON.parse(JSON.stringify(doc.toJSON())));assert.equal(back.firstChild.firstChild.marks[0].attrs.fontFamily,'Menksoft');assert.equal(back.firstChild.firstChild.marks[0].attrs.fontSize,40);});
test('punctuation runs are detected as ranges',()=>{const runs=c.punctuationRuns('ᠮᠣᠩᠭᠣᠯ“引号”，中文。');assert.equal(runs.length,3);assert.equal(runs[0].from,6);assert.equal(runs[0].to,7);assert.equal(runs[1].from,9);assert.equal(runs[1].to,11);assert.equal(runs[2].from,13);assert.equal(runs[2].to,14);});
test('Mongolian punctuation is flagged separately',()=>{const runs=c.punctuationRuns('ᠮᠣᠩᠭᠣᠯ᠃ ᠪᠢᠴᠢᠭ᠂');assert.ok(runs.length>=1);assert.equal(runs[0].mongolian,true);});
test('letters are never tagged as punctuation',()=>{assert.equal(c.punctuationRuns('ᠮᠣᠩᠭᠣᠯabc中文').length,0);});
test('consecutive punctuation forms one run',()=>{const runs=c.punctuationRuns('ᠮᠣᠩᠭᠣᠯ“”，。ᠪᠢᠴᠢᠭ');assert.equal(runs.length,1);assert.equal(runs[0].from,6);});
test('punct shift is clamped to ±0.5 em',()=>{assert.equal(c.safePunctShift(-9),-0.5);assert.equal(c.safePunctShift(9),0.5);assert.equal(c.safePunctShift(-0.15),-0.15);assert.equal(c.safePunctShift('x'),-0.15);});
test('punct scale is clamped',()=>{assert.equal(c.safeLeadingScale(9),1.6);assert.equal(c.safeLeadingScale(0.1),0.8);assert.equal(c.safeLeadingScale(0.85),0.85);});
test('punct settings default and round trip',()=>{const d=c.validateFile({format:'mori-document',version:2,title:'T',profile:'2023',settings:{punctShift:-0.3,punctScale:0.85},doc:c.textDocument('“x”').toJSON()});assert.equal(d.settings.punctShift,-0.3);assert.equal(d.settings.punctScale,0.85);const e=c.validateFile({format:'mori-document',version:2,title:'T',profile:'2023',doc:c.textDocument('x').toJSON()});assert.equal(e.settings.punctShift,-0.15);assert.equal(e.settings.punctScale,1);});
test('pagination reports units used per page',()=>{const r=c.paginateBlocks([{length:100,weight:2},{length:100,weight:2},{length:100,weight:1}],{contentHeight:1000,capacity:4});assert.deepEqual(r.pageUnits,[4,1]);assert.deepEqual(r.pages,[[0,1],[2]]);});
test('page units match page count',()=>{const r=c.paginateBlocks(Array.from({length:9},()=>({length:100,weight:1})),{contentHeight:1000,capacity:4});assert.equal(r.pageUnits.length,r.pages.length);assert.equal(r.pageUnits.reduce((a,b)=>a+b,0),9);});
test('empty document reports zero units',()=>{const r=c.paginateBlocks([],{contentHeight:100,capacity:1});assert.deepEqual(r.pageUnits,[0]);});
const result={ok:count===tests.length,passed:count,total:tests.length,tests};fs.writeFileSync(path.join(__dirname,'core-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));process.exitCode=result.ok?0:1;
