import {EditorState,TextSelection,AllSelection} from 'prosemirror-state';
import fallbackFont from '../vendor/NotoSansMongolian-Regular.ttf';
import {EditorView} from 'prosemirror-view';
import {DOMSerializer} from 'prosemirror-model';
import {baseKeymap,toggleMark,setBlockType,chainCommands,exitCode} from 'prosemirror-commands';
import {keymap} from 'prosemirror-keymap';
import {history,undo,redo} from 'prosemirror-history';
import {wrapInList,splitListItem,liftListItem} from 'prosemirror-schema-list';
import {schema,profiles,plainText,textDocument,inspectText,decodeBytes,b64ToBytes,bytesToB64,validateFile,initConverter,convertText,escapeHTML} from './core.js';

const $=id=>document.getElementById(id), native=!!window.webkit?.messageHandlers?.mori;
let seq=0,pending=new Map(),dirty=false,revision=0,draftTimer,composing=false,fonts=[],profile='2023',originals=[],converterVersion='unavailable';
let settings={font:'Mori Noto',size:28,leading:1.8,alignment:'start',margin:48,page:'A4'};
let latestSavedRevision=0,conversionLog=[];
window.moriNativeReply=({id,result,error})=>{const p=pending.get(id);if(!p)return;pending.delete(id);error?p.reject(new Error(error)):p.resolve(result);};
function bridge(action,payload={}){if(!native)return Promise.reject(new Error('此功能请在 Mori Mac 应用中使用。浏览器仅提供编辑预览。'));return new Promise((resolve,reject)=>{const id=String(++seq);pending.set(id,{resolve,reject});window.webkit.messageHandlers.mori.postMessage({id,action,payload});});}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,5000);}
function fail(e){toast(e.message||String(e));console.error(e);}
function run(fn){return (...args)=>Promise.resolve().then(()=>fn(...args)).catch(fail);}
async function confirm(message,detail=''){return native?bridge('confirm',{message,detail}):window.confirm(message+'\n'+detail);}
function markDirty(){dirty=true;revision++;$('saveState').textContent=native?'有修改 · 等待备份':'浏览器预览 · 尚未保存';if(native)bridge('dirty',{dirty:true}).catch(fail);clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,900);}
function serialize(){return {format:'mori-document',version:1,title:$('docTitle').value.slice(0,200)||'未命名',profile,settings,doc:view.state.doc.toJSON(),originals,conversionLog,savedAt:new Date().toISOString()};}
function documentJSON(data,pretty=false){const content=JSON.stringify(data,null,pretty?2:undefined);if(new TextEncoder().encode(content).length>64*1024*1024)throw new Error('文档超过64MB，无法安全保存和重开。请分拆内容。');return content;}
async function saveDraft(){if(!native||composing)return;const r=revision;try{await bridge('draftSave',{content:documentJSON(serialize())});if(r===revision)$('saveState').textContent=dirty?'恢复副本已备份 · 请保存文档':'文档已保存';}catch(e){$('saveState').textContent='恢复副本备份失败';fail(e);}}
function plugins(){return [history(),keymap({'Mod-z':undo,'Mod-Shift-z':redo,'Mod-y':redo,'Mod-b':toggleMark(schema.marks.strong),'Mod-i':toggleMark(schema.marks.em),'Mod-u':toggleMark(schema.marks.underline),'Enter':chainCommands(splitListItem(schema.nodes.list_item),baseKeymap.Enter),'Mod-[':liftListItem(schema.nodes.list_item),'Shift-Enter':chainCommands(exitCode,(state,dispatch)=>{dispatch?.(state.tr.replaceSelectionWith(schema.nodes.hard_break.create()).scrollIntoView());return true;})}),keymap(baseKeymap)];}
const sample=schema.node('doc',null,[
 schema.node('heading',{level:1},schema.text('ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ')),
 schema.node('paragraph',null,schema.text('ᠰᠠᠢᠨ ᠪᠠᠢᠨ᠎ᠠ ᠤᠤ᠂ ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ᠃')),
 schema.node('paragraph',null,schema.text('ᠲᠡᠭᠷᠢ ᠭᠠᠵᠠᠷ ᠤᠰᠤ ᠠᠭᠤᠯᠠ ᠲᠠᠯ᠎ᠠ ᠨᠤᠲᠤᠭ᠃')),
 schema.node('paragraph',null,schema.text('ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ ᠪᠢᠴᠢᠭ ᠰᠤᠶᠤᠯ᠃')),
 schema.node('paragraph',null,schema.text('在这里，让文字沿着自己的方向生长。'))
]);
const view=new EditorView($('editor'),{state:EditorState.create({schema,doc:sample,plugins:plugins()}),attributes:{lang:'mn-Mong',spellcheck:'false','aria-label':'蒙古文竖排富文本编辑器','data-placeholder':'开始书写…'},dispatchTransaction(tr){view.updateState(view.state.apply(tr));if(tr.docChanged)markDirty();updateStats();},handleDOMEvents:{compositionstart(){composing=true;$('compositionStatus').textContent='正在组字 · 保留输入法候选';return false;},compositionend(){composing=false;$('compositionStatus').textContent='系统输入法就绪';clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,1000);return false;}}});
function busy(){if(composing||view.composing){toast('请先完成输入法组字，再执行此操作。');return true;}return false;}
function updateStats(){const t=plainText(view.state.doc),stats=inspectText(t);$('charCount').textContent=stats.characters;$('wordCount').textContent=stats.words;$('puaCount').textContent=stats.pua;const {from,to}=view.state.selection;const selected=from===to?view.state.doc.textBetween(Math.max(0,from-2),from,'',''):view.state.doc.textBetween(from,to,'\n');$('selectionCodes').textContent=Array.from(selected).slice(0,22).map(c=>'U+'+c.codePointAt(0).toString(16).toUpperCase().padStart(4,'0')).join(' ')||'请选择文字以查看码点';const marks=view.state.storedMarks||view.state.selection.$from.marks();for(const [command,type] of [['bold','strong'],['italic','em'],['underline','underline']]){const b=document.querySelector(`[data-command="${command}"]`);const on=marks.some(m=>m.type===schema.marks[type]);b.setAttribute('aria-pressed',String(on));b.classList.toggle('active',on);} }
function applySettings(){const font=JSON.stringify(settings.font)+', "Mori Noto", sans-serif';document.documentElement.style.setProperty('--doc-font',font);document.documentElement.style.setProperty('--doc-size',settings.size+'px');document.documentElement.style.setProperty('--doc-leading',settings.leading);document.documentElement.style.setProperty('--doc-margin',settings.margin+'px');view.dom.style.textAlign=settings.alignment;view.dom.style.height=settings.page==='A3'?'720px':'520px';view.dom.style.minWidth=settings.page==='A3'?'1100px':'840px';$('fontPreview').style.fontFamily=font;$('fontSelect').value=settings.font;$('fontSize').value=settings.size;$('lineHeight').value=settings.leading;$('lineHeight1').value=settings.leading;$('alignment').value=settings.alignment;$('pageMargin').value=settings.margin;$('pageSize').value=settings.page;$('paperLabel').textContent='横向连续画布 · '+settings.page+' 参考版心';$('paper').style.zoom=Number($('zoom').value)/100;}
function applyProfile(){for(const b of document.querySelectorAll('[data-profile]')){const active=b.dataset.profile===profile;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}$('encodingStatus').textContent=profiles[profile].label+' · 原文保留';$('encodingHint').textContent=profiles[profile].detail;}
function load(data){const d=validateFile(data);view.updateState(EditorState.create({schema,doc:d.doc,plugins:plugins()}));settings=d.settings;profile=d.profile;originals=d.originals;conversionLog=Array.isArray(d.conversionLog)?d.conversionLog:[];$('docTitle').value=d.title;renderFonts();applySettings();applyProfile();updateTitle();updateStats();}
function updateTitle(){document.querySelector('.document-card h3').textContent=$('docTitle').value||'未命名';}
function renderFonts(){const filter=$('fontFilter').value;const list=fonts.filter(f=>filter==='all'||(filter==='pua'?f.hasPUA:f.hasMongolian));$('fontSelect').replaceChildren(new Option('Noto Sans Mongolian · 内置','Mori Noto'));const seen=new Set(['Mori Noto']);for(const f of list){if(!f.postscript||seen.has(f.postscript))continue;seen.add(f.postscript);$('fontSelect').add(new Option(f.family+' · '+f.postscript,f.postscript));}if(!seen.has(settings.font))$('fontSelect').add(new Option(settings.font+' · 文档指定',settings.font));$('fontCount').textContent=list.length+' 个字形';$('fontSelect').value=settings.font;}
function exec(command){if(busy())return;const map={undo,redo,bold:toggleMark(schema.marks.strong),italic:toggleMark(schema.marks.em),underline:toggleMark(schema.marks.underline),heading:setBlockType(schema.nodes.heading,{level:1}),paragraph:setBlockType(schema.nodes.paragraph),bullet:wrapInList(schema.nodes.bullet_list)};if(map[command]){map[command](view.state,view.dispatch,view);view.focus();}}
function showModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function hideModal(){$('modal').close();}
function guardUnsaved(){return !dirty?Promise.resolve(true):confirm('替换当前工作区？','当前文档有未保存修改。建议先取消并保存 .mglx 文档。');}
async function save(){if(busy())return;const r=revision;const d=serialize();if(!native){download(d.title+'.mglx',documentJSON(d,true),'application/json');toast('已发起文档下载；浏览器不提供原生恢复副本。');return;}const result=await bridge('save',{name:d.title,content:documentJSON(d,true),kind:'mglx'});if(result.cancelled)return;if(revision===r){dirty=false;latestSavedRevision=r;await bridge('dirty',{dirty:false});$('saveState').textContent='文档已保存';}toast('已保存 '+result.name);}
function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportText(){if(busy())return;showModal('导出文档','<p>文本导出为 UTF-8。当前蒙古文码点保持不变；需要转换时，请先使用编码转换预览。</p><div class="modal-actions"><button id="exportUTF8" class="button button-primary">导出 UTF-8 文本</button><button id="exportHTML" class="button">导出版式 HTML</button></div><p class="field-note">.txt 不包含格式；.mglx 保留格式和导入原始字节。此版本不提供 DOCX 互转。</p>');$('exportUTF8').onclick=run(async()=>{hideModal();const content=plainText(view.state.doc);if(native)await bridge('save',{name:$('docTitle').value,content,kind:'txt'});else download($('docTitle').value+'.txt',content);});$('exportHTML').onclick=run(async()=>{hideModal();const content=printHTML();if(native)await bridge('save',{name:$('docTitle').value,content,kind:'html'});else download($('docTitle').value+'.html',content,'text/html');});}
function printHTML(){const holder=document.createElement('div');holder.append(DOMSerializer.fromSchema(schema).serializeFragment(view.state.doc.content));const font='"'+settings.font.replace(/[^a-zA-Z0-9 _-]/gu,c=>'\\'+c.codePointAt(0).toString(16)+' ')+'"';return `<!doctype html><html lang="mn-Mong"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; font-src 'self' data:"><title>${escapeHTML($('docTitle').value)}</title><style>@font-face{font-family:'Mori Noto';src:url('data:font/ttf;base64,${fallbackFont}')}@page{size:A4 landscape;margin:15mm}body{margin:0;background:white;color:#26312c}.document{writing-mode:vertical-lr;text-orientation:mixed;direction:ltr;height:175mm;min-width:250mm;font-family:${font},'Mori Noto',sans-serif;font-size:${settings.size}px;line-height:${settings.leading};text-align:${settings.alignment}}p{margin:0 0 0 18px}h1{font-size:48px;margin:0 0 0 28px}h2{font-size:32px}</style></head><body><div class="document">${holder.innerHTML}</div></body></html>`;}
async function print(){if(busy())return;if(!native){toast('打印 / PDF 请在 Mac 应用中使用。');return;}if(!await confirm('使用系统打印 / 另存为 PDF','当前为横向连续画布，长文尚未实现 Word 式自动分页。请在系统打印预览中检查纸张、缩放与是否截断。'))return;await bridge('print',{html:printHTML()});}
async function open(){if(busy()||!await guardUnsaved())return;if(native){const r=await bridge('open');if(!r.cancelled)await receiveFile(r);}else $('fileInput').click();}
async function receiveFile(file){const bytes=b64ToBytes(file.base64);if(bytes.length>(file.name.toLowerCase().endsWith('.mglx')?64:20)*1024*1024)throw new Error('文本限制20MB，Mori文档限制64MB');if(file.name.toLowerCase().endsWith('.mglx')){load(decodeBytes(bytes).text);dirty=false;revision++;if(native)await bridge('dirty',{dirty:false});$('saveState').textContent='已打开文档';return;}
 showModal('打开文本 · 明确源编码',`<p>${escapeHTML(file.name)} · ${(bytes.length/1024).toFixed(1)} KB</p><label>字节编码<select id="importBytes"><option value="auto">自动（只识别 UTF-8 / UTF-16 BOM）</option><option value="utf-8">UTF-8</option><option value="utf-16le">UTF-16 LE</option><option value="utf-16be">UTF-16 BE</option><option value="gb18030">GB18030（系统解码器，未做2022版认证）</option></select></label><label>蒙古文约定<select id="importProfile"><option value="2023">国标2023 · Unicode 原文</option><option value="2010">国标2010 · 原文保留</option><option value="menksoft">蒙科立 · 私用区原文</option></select></label><p class="field-note">导入不转换蒙古文；原始字节会随 .mglx 保留。蒙科立文本需匹配字体。</p><button id="importCommit" class="button button-primary">保留原文并打开</button><p id="importError" role="alert"></p>`);
 $('importCommit').onclick=async()=>{try{const decoded=decodeBytes(bytes,$('importBytes').value);const p=$('importProfile').value;load({format:'mori-document',version:1,title:file.name.replace(/\.[^.]+$/,''),profile:p,settings,doc:textDocument(decoded.text).toJSON(),originals:[{name:file.name,base64:file.base64,byteEncoding:decoded.encoding,profile:p}]});hideModal();markDirty();toast('原文已保留；保存 .mglx 可保留导入原始字节。');}catch(e){$('importError').textContent=e.message;}};
}
function compatibility(){const s=inspectText(plainText(view.state.doc));const selected=fonts.find(f=>f.postscript===settings.font);showModal('兼容性与实现边界',`<div class="compat-grid"><section><h3>已实现</h3><ul><li>竖排富文本：上 → 下，列从左 → 右</li><li>本机字体枚举；内置 OFL Noto 兜底字体</li><li>Unicode / UTF-8 / UTF-16 原文读写与控制符保留</li><li>蒙科立 MenkShape / MenkLetter 显式转换预览</li><li>本机输入法组字事件接入，组字期间禁止转换</li></ul></section><section><h3>尚未认证或实现</h3><ul><li>GB/T 25914-2023 全项字形符合性</li><li>2010 ↔ 2023 自动字形约定迁移</li><li>GB18030-2022 全项及修改单符合性</li><li>托忒、锡伯、满文完整转换</li><li>各企业输入法实机认证；Windows 输入法不能直接在 Mac 运行</li><li>DOCX、表格、修订、自动分页与长文 PDF 保真</li></ul></section></div><p>当前私用区字符：${s.pua}；控制字符：${s.controls}。${selected?'当前字体蒙古文样本覆盖：'+(selected.hasMongolian?'通过':'未通过'):'当前使用内置字体或文档指定字体。'} 覆盖样本仅检查码位，不代表字形标准认证。</p><p class="field-note">国标2010/2023并非 Unicode 版本号；两者分别对应 GB/T 25914 的字形与控制约定。UTN #57 是技术说明，不等于国标认证。切换顶部配置仅改变文档元数据，不会转换正文。</p><p class="field-note">转换引擎：Satsrag/mongol-convert ${escapeHTML(converterVersion)}（Apache-2.0）；编辑引擎：ProseMirror（MIT）；Noto Sans Mongolian（SIL OFL 1.1）。转换可能改变名义字母并产生不可逆信息损失，须核对预览。未捆绑商业字体、词库或输入法。</p><div class="modal-actions"><button id="exportOriginal" class="button">导出首个导入原始文件</button></div>`);$('exportOriginal').disabled=!originals.length;$('exportOriginal').onclick=run(async()=>{const o=originals[0];hideModal();if(native)await bridge('save',{name:o.name,base64:o.base64,kind:'txt'});else download(o.name,b64ToBytes(o.base64),'application/octet-stream');});}
function conversion(){if(busy())return;const source=plainText(view.state.doc);showModal('编码转换 · 先预览，再导出',`<p class="warning">此转换按字形中转，可能改变名义字母。不会修改正文；导出结果必须由熟悉蒙古文的使用者校对。不能将 UTN57 直接标为完整国标2023。</p><div class="conversion-fields"><label>源约定<select id="convFrom"><option value="utn57">Unicode · UTN57</option><option value="menk_shape">蒙科立 MenkShape（PUA字形）</option><option value="menk_letter">蒙科立 MenkLetter</option><option value="delehi">德力海 Delehi</option><option value="z52">Z52</option><option value="zvvnmod">ZVVNMOD</option></select></label><label>目标约定<select id="convTo"><option value="menk_shape">蒙科立 MenkShape</option><option value="utn57">Unicode · UTN57</option><option value="menk_letter">蒙科立 MenkLetter</option><option value="delehi">德力海 Delehi</option><option value="z52">Z52</option><option value="zvvnmod">ZVVNMOD</option></select></label></div><button id="convRun" class="button button-primary">生成预览</button><p id="convSummary" role="status">原文保留，未进行转换。</p><textarea id="convPreview" readonly aria-label="转换结果"></textarea><pre id="convWarnings"></pre><button id="convExport" class="button" disabled>导出转换结果（UTF-8）</button>`);$('convFrom').value=profile==='menksoft'?'menk_shape':'utn57';$('convTo').value=profile==='menksoft'?'utn57':'menk_shape';let result=null;
 $('convRun').onclick=run(()=>{result=convertText($('convFrom').value,$('convTo').value,source);$('convPreview').value=result.text;$('convPreview').style.fontFamily=JSON.stringify(settings.font)+', "Mori Noto"';const left=inspectText(result.text).pua;$('convSummary').textContent=`生成 ${Array.from(result.text).length} 字符 · ${result.warnings.length} 条引擎警告 · 结果私用区 ${left} 字符`;$('convWarnings').textContent=result.warnings.join('\n')||'无引擎警告不等于无损。未映射字符可能原样通过；请核对码点与字形。';$('convExport').disabled=false;});
 for(const id of ['convFrom','convTo'])$(id).onchange=()=>{result=null;$('convExport').disabled=true;$('convPreview').value='';};
 $('convExport').onclick=run(async()=>{if(!result)return;const text=result.text,mode=$('convTo').value;hideModal();if(!await confirm('导出经过字形转换的副本？','源文档不改变；导出结果不保证无损，请勿覆盖唯一原件。'))return;if(native)await bridge('save',{name:$('docTitle').value+'-'+mode,content:text,kind:'txt'});else download($('docTitle').value+'-'+mode+'.txt',text);});
}
function findMatches(query){const out=[];if(!query)return out;view.state.doc.descendants((node,pos)=>{if(!node.isTextblock)return;let text='',positions=[];node.descendants((child,offset)=>{if(child.isText){text+=child.text;for(let i=0;i<child.text.length;i++)positions.push(pos+1+offset+i);}else if(child.type===schema.nodes.hard_break){text+='\n';positions.push(pos+1+offset);}});for(let i=0;(i=text.indexOf(query,i))!==-1;i+=query.length){out.push({from:positions[i],to:positions[i+query.length-1]+1});}return false;});return out;}
function findNext(){if(busy())return;const matches=findMatches($('findInput').value);$('findResult').textContent=matches.length+' 处';if(!matches.length)return;const target=matches.find(m=>m.from>=view.state.selection.to)||matches[0];view.dispatch(view.state.tr.setSelection(TextSelection.create(view.state.doc,target.from,target.to)).scrollIntoView());view.focus();}
async function replaceAll(){if(busy())return;const matches=findMatches($('findInput').value),replacement=$('replaceInput').value;if(!matches.length)return toast('没有匹配项');if(!await confirm('替换全部 '+matches.length+' 处？','替换可撤销，不跨越段落匹配。'))return;let tr=view.state.tr;for(const m of matches.reverse())tr.insertText(replacement,m.from,m.to);view.dispatch(tr);$('findResult').textContent='已替换 '+matches.length+' 处';view.focus();}
function setTab(tab){for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===tab);if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}for(const name of ['home','insert','layout'])$(name+'Toolbar').hidden=name!==tab;if(tab==='encoding'){ $('homeToolbar').hidden=false;conversion();}}
const commands={new:async()=>{if(busy()||!await guardUnsaved())return;load({format:'mori-document',version:1,title:'未命名文档',profile:'2023',settings,doc:textDocument('').toJSON()});markDirty();view.focus();},open,save,exportText,print,undo:()=>exec('undo'),redo:()=>exec('redo'),find:()=>{$('findBar').hidden=!$('findBar').hidden;$('findToggle').setAttribute('aria-expanded',String(!$('findBar').hidden));if(!$('findBar').hidden)$('findInput').focus();},compatibility,convert:conversion};
window.moriCommand=command=>run(commands[command]||(()=>{}))();
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>window.moriCommand(b.dataset.action);
for(const b of document.querySelectorAll('[data-command]')){b.onmousedown=e=>e.preventDefault();b.onclick=()=>exec(b.dataset.command);}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>setTab(b.dataset.tab);
for(const b of document.querySelectorAll('[data-profile]'))b.onclick=()=>{if(busy())return;profile=b.dataset.profile;applyProfile();markDirty();toast('仅切换文档配置；原文未转换。');};
for(const b of document.querySelectorAll('[data-insert]')){b.onmousedown=e=>e.preventDefault();b.onclick=()=>{if(busy())return;view.dispatch(view.state.tr.insertText(String.fromCodePoint(parseInt(b.dataset.insert,16))).scrollIntoView());view.focus();};}
for(const [id,key] of [['fontSelect','font'],['fontSize','size'],['lineHeight','leading'],['lineHeight1','leading'],['alignment','alignment'],['pageMargin','margin'],['pageSize','page']])$(id).onchange=()=>{settings[key]=['size','leading','margin'].includes(key)?Number($(id).value):$(id).value;applySettings();markDirty();};
$('fontFilter').onchange=renderFonts;$('docTitle').maxLength=200;$('docTitle').oninput=()=>{updateTitle();markDirty();};$('textColor').oninput=()=>{if(busy())return;toggleMark(schema.marks.ink,{color:$('textColor').value})(view.state,view.dispatch);view.focus();};
$('guides').onchange=()=>{$('paper').classList.toggle('show-guides',$('guides').checked);view.dom.style.outline=$('guides').checked?'1px dashed #9eac8d':'';};$('zoom').onchange=applySettings;
$('findNext').onclick=findNext;$('findInput').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing&&e.keyCode!==229)findNext();};$('replaceAll').onclick=run(replaceAll);$('findClose').onclick=()=>{$('findBar').hidden=true;$('findToggle').setAttribute('aria-expanded','false');};$('modalClose').onclick=hideModal;
$('fileInput').onchange=run(async()=>{const f=$('fileInput').files[0];if(f){if(f.size>(f.name.toLowerCase().endsWith('.mglx')?64:20)*1024*1024)throw new Error('文本限制20MB，Mori文档限制64MB');await receiveFile({name:f.name,base64:bytesToB64(new Uint8Array(await f.arrayBuffer()))});}$('fileInput').value='';});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&['s','o','p','f'].includes(e.key.toLowerCase())&&!e.isComposing){e.preventDefault();window.moriCommand({s:'save',o:'open',p:'print',f:'find'}[e.key.toLowerCase()]);}});
window.addEventListener('beforeunload',e=>{if(dirty&&!native){e.preventDefault();e.returnValue='';}});

window.moriSmokeTest=async()=>{const checks=[],check=(name,pass)=>checks.push({name,pass:!!pass});const before=serialize();const original=plainText(view.state.doc);check('vertical-lr writing mode',getComputedStyle(view.dom).writingMode==='vertical-lr');check('left-to-right direction',getComputedStyle(view.dom).direction==='ltr');check('fallback font loaded',document.fonts.check('28px "Mori Noto"'));check('converter 0.7.1',converterVersion==='0.7.1');
 const complex='ᠮᠣᠩᠭᠣᠯ\u180B\u180C\u180D\u180E\u180F\u202F\u200D\u200C 😀 中文';check('Unicode scalar count',inspectText('ᠮ😀').characters===2);check('UTF8 round trip',decodeBytes(new TextEncoder().encode(complex)).text===complex);check('UTF16 BOM detection',decodeBytes(Uint8Array.from([255,254,32,24])).text==='ᠠ');check('invalid UTF8 rejected',(()=>{try{decodeBytes(Uint8Array.from([255]));return false;}catch{return true;}})());check('GB18030 decoder basic',decodeBytes(Uint8Array.from([0xd6,0xd0]),'gb18030').text==='中');
 view.dispatch(view.state.tr.insertText(complex,view.state.doc.content.size-1));check('insert control characters intact',plainText(view.state.doc).includes(complex));undo(view.state,view.dispatch);check('undo restores document',plainText(view.state.doc)===original);redo(view.state,view.dispatch);check('redo control characters',plainText(view.state.doc).includes(complex));const saved=validateFile(serialize());check('document JSON roundtrip',plainText(saved.doc)===plainText(view.state.doc));const nativeContent=JSON.stringify(serialize());if(native){await bridge('draftSave',{content:nativeContent});check('native isolated draft readback',(await bridge('draftLoad')).content===nativeContent);check('native font enumeration',fonts.length>0);}
 const menk=convertText('utn57','menk_shape','ᠮᠣᠩᠭᠣᠯ');check('Menksoft conversion produces PUA',inspectText(menk.text).pua>0);const back=convertText('menk_shape','utn57',menk.text);check('Menksoft converts back to Mongolian',/[\u1820-\u1842]/u.test(back.text));check('unrelated text preserved by converter',convertText('menk_shape','utn57','中文 ABC 😀').text==='中文 ABC 😀');
 view.dispatch(view.state.tr.setSelection(new AllSelection(view.state.doc)));toggleMark(schema.marks.strong)(view.state,view.dispatch);check('rich formatting',JSON.stringify(view.state.doc.toJSON()).includes('strong'));load(before);for(const p of Object.keys(profiles)){profile=p;applyProfile();check('profile preserves codepoints '+p,plainText(view.state.doc)===original);}profile=before.profile;applyProfile();
 check('lossy conversion produces explicit warning',menk.roundTripExact===false&&menk.warnings.length>0);
 const testDoc=schema.node('doc',null,[schema.node('paragraph',null,[schema.text('AB',[schema.marks.strong.create()]),schema.text('CD')])]);view.updateState(EditorState.create({schema,doc:testDoc,plugins:plugins()}));check('search across inline formatting',findMatches('BCD').length===1&&findMatches('BCD')[0].from===2);
 $('findInput').value='BC';const selectionBefore=view.state.selection.from;$('findInput').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));check('find does not steal IME confirmation',view.state.selection.from===selectionBefore);
 conversion();$('convRun').click();await new Promise(r=>setTimeout(r,20));check('conversion dialog preview',!$('convExport').disabled&&$('convPreview').value.length>0);hideModal();
 const printDoc=new DOMParser().parseFromString(printHTML(),'text/html');check('print font CSS not HTML-escaped',!printDoc.querySelector('style').textContent.includes('&quot;'));check('HTML export embeds fallback font',printDoc.querySelector('style').textContent.includes('data:font/ttf;base64,'));
 load(before);dirty=false;clearTimeout(draftTimer);if(native)await bridge('dirty',{dirty:false});$('saveState').textContent='本地工作区 · 离线就绪';view.dispatch(view.state.tr.setSelection(TextSelection.atStart(view.state.doc)));view.dom.blur();await document.fonts.ready;return {ok:checks.every(c=>c.pass),checks,fonts:fonts.filter(f=>f.hasMongolian).map(f=>f.family).filter((v,i,a)=>a.indexOf(v)===i),conversionExample:{source:'ᠮᠣᠩᠭᠣᠯ',privateUse:menk.text,result:back.text,warnings:back.warnings},boundary:'Smoke tests are not national-standard conformance or vendor IME certification.'};};
async function boot(){try{converterVersion=initConverter();}catch(e){fail(e);}$('previewNote').hidden=native;if(native){try{fonts=await bridge('fonts');}catch(e){fail(e);}try{const draft=await bridge('draftLoad');if(draft.content){const parsed=validateFile(draft.content);load({...parsed,doc:parsed.doc.toJSON()});dirty=true;await bridge('dirty',{dirty:true});$('saveState').textContent='已恢复副本 · 请另存文档';}}catch(e){toast('恢复副本读取失败；原文件未改动：'+e.message);}}renderFonts();applySettings();applyProfile();updateStats();await document.fonts.ready;window.moriReady=true;}
boot().catch(fail);
